### ISSUE TITLE
Problem in Nextcloud version 25.0.6 Enterprise with SSO & SAML authentication

### ISSUE THREAD

**Issue by sudo-gedit** [nextcloud/password_policy#472] opened 2023-05-16 10:20 UTC
### Steps to reproduce
1. Install Nextcloud 25.0.6
2. Install Plugin Password Policy
3. Install Plugin SSO & SAML authentication
4. Login over SSO

### Expected behaviour
It is possible to log in.

### Actual behaviour
It is not possible to log in via SSO.

The plugin also controls the password policy. Unfortunately, without the plugin we cannot enforce the password policy of our company. That's why the login error should be fixed.

### Server configuration

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "activity_expire_days": 14,
    "auth.bruteforce.protection.enabled": true,
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "trusted_domains": [
       "XXX"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "25.0.6.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "proxy": "XXX",
    "filelocking.enabled": "true",
    "mail_smtpauthtype": "PLAIN",
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED_FOR"
    ],
    "logtimezone": "UTC",
    "log_type": "file",
    "logfile": "\/var\/www\/html\/nextcloud_data\/nextcloud.log",
    "debug": "false",
    "knowledgebaseenabled": false,
    "log_rotate_size": "104857600",
    "loglevel": 2,
    "log_query": false,
    "cron_log": true,
    "enable_previews": true,
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "updater.release.channel": "enterprise",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "appcodechecker": true,
    "session_keepalive": true,
    "htaccess.RewriteBase": "\/",
    "theme": "",
    "mysql.utf8mb4": true,
    "versions_retention_obligation": "auto, 30",
    "trashbin_retention_obligation": "auto, 30",
    "lost_password_link": "disabled",
    "default_phone_region": "DE",
    "updater.server.url": "XXX"
    "encryption.legacy_format_support": false,
    "encryption.key_storage_migrated": false,
    "encryption_skip_signature_check": true,
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "XXX",
    "overwriteprotocol": "https",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}

**Operating system**:
Debian GNU/Linux 11

**Web server:**
Apache2 (2.4.56-1~deb11u2 )

**Database:**
MariaDB (1:10.5.19-0+deb11u2)

**PHP version:**
PHP (1:8.0.28-1+0~20230409.51+debian11~1.gbp452b35 )

**Nextcloud version:** 
25.0.6 Enterprise

**Where did you install Nextcloud from:**
According to Nextcloud documentation

**List of activated apps:**
Enabled:
 - activity: 2.17.0
 - admin_audit: 1.15.0
 - bruteforcesettings: 2.5.0
 - checksum: 1.2.1
 - circles: 25.0.0
 - cloud_federation_api: 1.8.0
 - comments: 1.15.0
 - contacts: 5.2.0
 - dav: 1.24.0
 - documentserver_community: 0.1.13
 - encryption: 2.13.0
 - federatedfilesharing: 1.15.0
 - files: 1.20.1
 - files_downloadlimit: 1.0.1
 - files_pdfviewer: 2.6.0
 - files_rightclick: 1.4.0
 - files_sharing: 1.17.0
 - files_trashbin: 1.15.0
 - files_versions: 1.18.0
 - impersonate: 1.12.0
 - logreader: 2.10.0
 - lookup_server_connector: 1.13.0
 - nextcloud_announcements: 1.14.0
 - oauth2: 1.13.0
 - onlyoffice: 7.8.0
 - photos: 2.0.1
 - privacy: 1.9.0
 - provisioning_api: 1.15.0
 - related_resources: 1.0.4
 - serverinfo: 1.15.0
 - settings: 1.7.0
 - sharebymail: 1.15.0
 - support: 1.8.0
 - survey_client: 1.13.0
 - systemtags: 1.15.0
 - text: 3.6.0
 - theming: 2.0.1
 - twofactor_backupcodes: 1.14.0
 - updatenotification: 1.15.0
 - user_ldap: 1.15.0
 - user_saml: 5.1.2
 - viewer: 1.9.0
 - weather_status: 1.5.0
 - workflowengine: 2.7.0
Disabled:
 - approval
 - contactsinteraction: 1.2.0
 - dashboard: 7.0.0
 - federation: 1.5.0
 - files_external
 - files_lock
 - firstrunwizard: 2.6.0
 - globalsiteselector
 - notifications: 2.6.0
 - password_policy: 1.15.0
 - recommendations: 0.4.0
 - suspicious_login
 - twofactor_totp
 - user_status: 1.0.1

**Comment by DoctorMcKay** [comment] 2023-05-25 02:55
Same issue here, I had to use `occ app:disable password_policy` to be able to login. From the error log:

```json
{
	"reqId": "qDtZf3Vji7fZBa8Ok2fS",
	"level": 3,
	"time": "2023-05-25T02:51:26+00:00",
	"remoteAddr": "-",
	"user": "-",
	"app": "index",
	"method": "GET",
	"url": "/",
	"message": "OCA\\Password_Policy\\ComplianceService::entryControl(): Argument #2 ($password) must be of type string, null given, called in /home/-/web/sites/-/webroot/apps/password_policy/lib/Listener/BeforeUserLoggedInEventListener.php on line 45",
	"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42",
	"version": "25.0.6.1",
	"exception": {
		"Exception": "TypeError",
		"Message": "OCA\\Password_Policy\\ComplianceService::entryControl(): Argument #2 ($password) must be of type string, null given, called in /home/-/web/sites/-/webroot/apps/password_policy/lib/Listener/BeforeUserLoggedInEventListener.php on line 45",
		"Code": 0,
		"Trace": [
			{
				"file": "/home/-/web/sites/-/webroot/apps/password_policy/lib/Listener/BeforeUserLoggedInEventListener.php",
				"line": 45,
				"function": "entryControl",
				"class": "OCA\\Password_Policy\\ComplianceService",
				"type": "->"
			},
			{
				"file": "/home/-/web/sites/-/webroot/lib/private/EventDispatcher/ServiceEventListener.php",
				"line": 87,
				"function": "handle",
				"class": "OCA\\Password_Policy\\Listener\\BeforeUserLoggedInEventListener",
				"type": "->"
			},
			{
				"file": "/home/-/web/sites/-/webroot/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
				"line": 251,
				"function": "__invoke",
				"class": "OC\\EventDispatcher\\ServiceEventListener",
				"type": "->"
			},
			{
				"file": "/home/-/web/sites/-/webroot/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
				"line": 73,
				"function": "callListeners",
				"class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
				"type": "->"
			},
			{
				"file": "/home/-/web/sites/-/webroot/lib/private/EventDispatcher/EventDispatcher.php",
				"line": 88,
				"function": "dispatch",
				"class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
				"type": "->"
			},
			{
				"file": "/home/-/web/sites/-/webroot/lib/private/EventDispatcher/EventDispatcher.php",
				"line": 100,
				"function": "dispatch",
				"class": "OC\\EventDispatcher\\EventDispatcher",
				"type": "->"
			},
			{
				"file": "/home/-/web/sites/-/webroot/lib/private/legacy/OC_User.php",
				"line": 192,
				"function": "dispatchTyped",
				"class": "OC\\EventDispatcher\\EventDispatcher",
				"type": "->"
			},
			{
				"file": "/home/-/web/sites/-/webroot/lib/private/legacy/OC_User.php",
				"line": 243,
				"function": "loginWithApache",
				"class": "OC_User",
				"type": "::",
				"args": [
					"*** sensitive parameters replaced ***"
				]
			},
			{
				"file": "/home/-/web/sites/-/webroot/lib/base.php",
				"line": 1103,
				"function": "handleApacheAuth",
				"class": "OC_User",
				"type": "::"
			},
			{
				"file": "/home/-/web/sites/-/webroot/lib/base.php",
				"line": 1037,
				"function": "handleLogin",
				"class": "OC",
				"type": "::"
			},
			{
				"file": "/home/-/web/sites/-/webroot/index.php",
				"line": 36,
				"function": "handleRequest",
				"class": "OC",
				"type": "::"
			}
		],
		"File": "/home/-/web/sites/-/webroot/apps/password_policy/lib/ComplianceService.php",
		"Line": 90,
		"CustomMessage": "--"
	}
}
```

**Comment by gonzalo** [comment] 2023-05-30 10:00
It failed for me in 25.0.6, and I had to disable plugin. I just upgraded to 25.0.7, enabled de password_policy app and it's working properly.

**Comment by joshtrichards** [comment] 2024-03-18 16:37
Duplicate of #448

**Closed by joshtrichards** 2024-03-18 16:37 UTC
